### ISSUE TITLE
Show progress bar when uploading/downloading files

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-client-py#23]
.

**Comment by FuZer** [comment]
I think ![tqdm](https://pypi.python.org/pypi/tqdm) will be helpful if the object is iterable.

**Comment by achimnol** [comment]
Thanks for information. I just implemented a nice-looking progress bar using tqdm, but need to polish the codes and tests as I migrated from requests to aiohttp because requests does not support streaming multi-part uploads (although an extra package called `requests_toolbelt` has it but it requires more adapation work...).

**Comment by achimnol** [comment]
Shipped in 1.3.4.
