### ISSUE TITLE
쿼리 요청이 불가능합니다.

### ISSUE THREAD

**Issue by like-sinsky** [lablup/backend.ai-client-py#39]
`from ai.backend.client import Kernel`로 되있으나 실제로는 
`from ai.backend.client.kernel import Kernel`해야 작동이 됩니다.
또한 위와 같이 변경하여 아래와 같이 요청을 시도하여도 
```
from ai.backend.client.kernel import Kernel

kern = Kernel.get_or_create('python', client_token='abcdef')
result = kern.execute('print("hello world")', mode='query')
print(result['console'])
kern.destroy()
```
`AssertionError: You must use API wrapper functions via a Session object.` 에러가 발생합니다.
get_or_create가 클래스 메소드이다보니 세션을 어느시점에 어떻게 넣어줘야 하는지 궁금합니다.

마지막으로 사소한 부분이긴 하나 실세 샘플 코드에서는 클라이언트 토큰이 'abc'로 적혀있는데
실제로 그대로 돌려볼경우 
`assert 4 <= len(client_token) <= 64, 'Client session token should be 4 to 64 characters long.'`
에러가 막히지 않을까 싶습니다. 그래서 4자 이상으로 변경하시면 처음 시도하시는 분이 에러없이 테스트 해보실수 있지 않을까 싶습니다.

**Comment by achimnol** [comment]
예제코드 막 업데이트했습니다!
https://github.com/lablup/backend.ai-client-py/blob/master/README.rst

실제 가장 자세한 사용 사례는 [run 명령어 구현](https://github.com/lablup/backend.ai-client-py/blob/master/src/ai/backend/client/cli/run.py)을 보시면 되겠습니다.

**Comment by like-sinsky** [comment]
감사합니다!
다만, 아래와 같이 stdout,stderr대신 sys.stdout, sys.stderr로 변경해야서 수정하시면 좋을거 같습니다.
```
import sys
from ai.backend.client import Session

with Session() as session:
    kern = session.Kernel.get_or_create('lua5', client_token='mysession')
    code = 'print("hello world")'
    mode = 'query'
    run_id = None
    while True:
        result = kern.execute(run_id, code, mode=mode)
        run_id = result['runId']  # keeps track of this particular run loop
        for rec in result.get('console', []):
            if rec[0] == 'stdout':
                print(rec[1], end='', file=sys.stdout)
            elif rec[0] == 'stderr':
                print(rec[1], end='', file=sys.stderr)
            else:
                handle_media(rec)
        if result['status'] == 'finished':
            break
        elif result['status'] == 'waiting-input':
            mode = 'input'
            if result['options'].get('is_password', False):
                code = getpass.getpass()
            else:
                code = input()
        else:
            mode = 'continued'
            code = ''
    kern.destroy()
```

**Comment by achimnol** [comment]
README 수정사항 반영하였습니다! 👍
