### ISSUE TITLE
Config displays the latest API version always

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-client-py#79]
`backend.ai config` command displays current settings including API endpoint and API version. However, the API version displays always the latest version (v5.20191215 for current master). For example, https://api.backend.ai endpoint currently serves v4.20181215 as shown below:

![image](https://user-images.githubusercontent.com/7539358/71616454-b0b93400-2bf9-11ea-924c-f8a55c7c8ead.png)

When running `backend.ai config`, you'll see API version of v5.20191215.

![image](https://user-images.githubusercontent.com/7539358/71616537-08579f80-2bfa-11ea-9b13-202ca06728fe.png)

I think we need to display the correct API version of the endpoint by fetching the information from the endpoint. Or, at least we need to provide users to be able to set API version by environment variables, such as `BACKEND_API_VERSION`.

**Comment by achimnol** [comment]
Fixed as part of #82.
